### ISSUE TITLE
执行build  的  报错 了 

### ISSUE THREAD

**Issue by yh4922** [woytu/NSIS_SetupSkin#1]
`
File: "logo.ico"->"logo.ico" [compress] 133352/458870 bytes
File: "..\app.7z" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
!include: error in script: "..\commonfunc.nsh" on line 138
!include: error in script: "ui.nsh" on line 14
Error in script "D:\Development\NSIS_Script\NSIS_SetupSkin-master\SetupScripts\nim\info.nsi" on line 21 -- aborting creation process
`
执行的 是 skin 下面的 nim 里面的nsi

**Comment by yh4922** [comment]
发现是因为  压缩  没有成功   我自己 去吧文件压缩 放进去 就可以 
有什么解决方案么 自己压缩太麻烦了

**Comment by bajins** [comment]
> `File: "logo.ico"->"logo.ico" [compress] 133352/458870 bytes File: "..\app.7z" -> no files found. Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] | /oname=outfile one_file_only) !include: error in script: "..\commonfunc.nsh" on line 138 !include: error in script: "ui.nsh" on line 14 Error in script "D:\Development\NSIS_Script\NSIS_SetupSkin-master\SetupScripts\nim\info.nsi" on line 21 -- aborting creation process`
> 执行的 是 skin 下面的 nim 里面的nsi

导入nsis脚本错误，晚点查一下什么问题

**Comment by bajins** [comment]
经测试没有问题

**Comment by bajins** [comment]
> 发现是因为 压缩 没有成功 我自己 去吧文件压缩 放进去 就可以
> 有什么解决方案么 自己压缩太麻烦了

目录下自带7z压缩，压缩应该是没有问题的
