### ISSUE TITLE
请教：NiuniuSetupskin的版权是哪种

### ISSUE THREAD

**Issue by songyinghao** [woytu/NSIS_SetupSkin#2]

**Comment by bajins** [comment]
不好意思，没有收到邮件提示，现在才看到，关于License请看这里：[http://www.ggniu.cn/articles/nsniuniuskin.html](http://www.ggniu.cn/articles/nsniuniuskin.html)

官网这样说到：
> nsNiuniuSkin是目前国内最专业的安装包UI控件，与NSIS完美融合。同时它也是一个完全免费的安装包UI控件，无任何的使用限制。我们的目标是让稍微有一点NSIS基础的人在一天内完成一个安装包制作。
