### ISSUE TITLE
求大佬联系方式

### ISSUE THREAD

**Issue by SilurianYang** [woytu/NSIS_SetupSkin#3]
有个问题 需要向大佬请教下 就是我需要对输出的目录进行标记写入权限。尝试代码如下 无效 求大佬联系方式 我的QQ 1606726660
```
	AccessControl::GrantOnFile \
		"$INSTDIR" "(BU)" "FullAccess"
	Pop $R0
        WriteRegStr HKCU "Software\aaaaaaaaa" "Path" "$INSTDIR"
	${If} $R0 == error
		Pop $R0
		WriteRegStr HKCU "Software\aaaaaaaaa" "Error" "AccessControl error: $R0"
  	${EndIf}

	${If} $R0 != error
    	        WriteRegStr HKCU "Software\aaaaaaaaa" "Success" "获取成功"
	${EndIf}
```
注册表是显示注册成功的 但是当前路径没有权限
![QQ截图20200321133501](https://user-images.githubusercontent.com/31280665/77220242-08bc6280-6b79-11ea-9e94-c689458a10d6.png)
![QQ截图20200321133444](https://user-images.githubusercontent.com/31280665/77220243-09ed8f80-6b79-11ea-998f-1ef7bb0b515d.png)

**Comment by bajins** [comment]
![image](https://user-images.githubusercontent.com/30252550/77220357-508fb980-6b7a-11ea-8fd9-ccd9490e6716.png)

你不是写入成功了吗？

**Comment by SilurianYang** [comment]
但是文件夹没有完全控制的权限啊

**Comment by bajins** [comment]
https://www.nsisfans.com/thread-8743-1-1.html

https://nsis.sourceforge.io/AccessControl_plug-in

你需要下载插件到NSIS\Plugins目录下

**Comment by SilurianYang** [comment]
# 换了一个方式解决了   谢谢大佬
