### ISSUE TITLE
electron用mac打包.exe,卸载的时候nsis报错

### ISSUE THREAD

**Issue by simple-YoungBadBoy** [woytu/NSIS_SetupSkin#4]
![image](https://user-images.githubusercontent.com/20324269/89714516-d6998900-d9d1-11ea-8efc-647539679f45.png)
大佬知道这是什么原因吗，求解答，折腾2天了呜呜

**Comment by bajins** [comment]
你看看是不是有什么必须的文件没有引入打包进去

**Comment by bajins** [comment]
> 你看看是不是有什么必须的文件没有引入打包进去

可能是你本地的卸载程序的包有丢失？还有一个是系统位数和软件的系统支持不相匹配，如果实在处理不了，你可以尝试一下更新nsis

**Comment by simple-YoungBadBoy** [comment]
多谢，这个问题解决了，我在Windows加上了环境，用Windows打包.exe就没问题了
