### ISSUE TITLE
如何获取打包后的 SHA512

### ISSUE THREAD

**Issue by yi-jy** [woytu/NSIS_SetupSkin#8]
你好，感谢你提供的这个项目！有个问题请教下，有办法在打包时像 electron-builder 那样生成 latest.yml 吗？因为 latest.yml 中包含了 SHA512 （base64 格式的）等字段，可用于动态更新版本。

我在使用你的这个项目打包后，只生成了安装包，没有生成类似 latest.yml 相关文件。于是，我尝试借助 nsisWeb 插件在打包时来生成 latest.yml 文件，但在打包时报错 Invalid command: nsisWeb::Publish。

我又尝试通过命令 `certutil -hashfile your_client_file.exe SHA512` 获取16进制的 SHA512 的哈希值，再把它转换为 base64 ，但好像值也对不上。

请问还有其他方案吗？

**Comment by bajins** [comment]
可使用命令`7z h -scrc* test.7z`获取哈希值

命令详见：https://microsoft.github.io/VirtualClient/docs/workloads/compression/7zip/#workload-usage

**Comment by yi-jy** [comment]
好的，问题已解决！
